### ISSUE TITLE
Minecraft 1.12.1 Error

### ISSUE THREAD

**Issue by GershonR** [antiAD/AntiAd#77]
```
[22:45:09] [Server thread/ERROR]: Could not load 'plugins/AntiAD-2.3.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.communitybuilt.punchstaff.PunchStaff'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[patched_1.12.1.jar:git-Paper-1192]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.1.jar:git-Paper-1192]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched_1.12.1.jar:git-Paper-1192]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.1.jar:git-Paper-1192]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [patched_1.12.1.jar:git-Paper-1192]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) [patched_1.12.1.jar:git-Paper-1192]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.1.jar:git-Paper-1192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: com.communitybuilt.punchstaff.PunchStaff
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_141]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.12.1.jar:git-Paper-1192]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.1.jar:git-Paper-1192]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_141]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_141]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched_1.12.1.jar:git-Paper-1192]
	... 7 more
```

**Comment by KasperFranz** [comment]
WHere did you download the file from?

there was a mixup in files at some point - so would like to remove the faulty file

**Comment by GershonR** [comment]
I got it from the BukkitDev page, latest plugin version

**Comment by KasperFranz** [comment]
As described in the other ticket I will realese this wekend with  a fix for this :)

**Comment by KasperFranz** [comment]
Can i get you to use the latest prerelease - https://github.com/antiAD/AntiAd/releases/tag/2.4.0-Pre

**Comment by KasperFranz** [comment]
is the pre release working @GershonR @zBoringDrop

**Comment by zBoringDrop** [comment]
Yes

**Comment by KasperFranz** [comment]
going to be pushed as a release then.
